### ISSUE TITLE
Eu tax shows zero but after order placed its automatically take default tax

### ISSUE THREAD

**Issue by siddhrock** [yireo/Magento_EU_Tax_Rates#12]
Hello team,
I am facing one issue when eu tax applied zero in checkout then its automatically take default tax after order placed

Please help me

**Comment by jissereitsma** [comment]
Unfortunately, this repository is just simply a listing of tax rates, not a software that helps you manage the actual tax rules that you have configured in the backend. I'll close this issue because your issue is definitely not related in anyway to this repository. Instead, I think you should be looking for a Magento professional that helps you configure rules in your backend and possibly troubleshoot your checkout. Sorry to not being able to help with this on a voluntary basis.
