### ISSUE TITLE
Croatia VAT rates

### ISSUE THREAD

**Issue by GoranJ24** [yireo/Magento_EU_Tax_Rates#14]
Hi,
Croatia has three VAT rates:
25%, 13% and 5%
5% rate is missing from the list (newspapers, drugs, mediacal, food /milk, oil.../, cinema tickets, etc)

**Comment by jissereitsma** [comment]
Thanks for pointing this out. Please note that opening an issue on GitHub is about the same time investment as making an actual Pull Request. So I definitely recommend you to get used to making Pull Requests, because it eases the work on the maintainers end (my end). Anyway, the change is now made: https://github.com/yireo/Magento_EU_Tax_Rates/commit/5c6de2b9c95f89a6b9a07dede86bff841b1435f9

**Comment by PascalBrouwers** [comment]
@jissereitsma might want to close this issue then ;)

**Comment by jissereitsma** [comment]
Done :)
