### ISSUE TITLE
Misleading info?

### ISSUE THREAD

**Issue by WastedCharlie** [yireo/Magento_EU_Tax_Rates#8]
Hi,
I happened upon this git during a Google search and got momentarily panicked, only to realise that the author may be misinformed:
From README.md
> Starting from 1st of January 2015, EU tax regulation changes. Instead of the original tax calculation, where the seller took the tax rate from his own country, the tax now needs to be based on the country of the seller. Within Magento, this simply means that the tax is calculated using tax rates that differ per EU country.

This statement makes no reference to the circumstances in which the rules have changed.  It is **not universal**; In fact, it is highly exceptional.

As a rule, one only pays VAT in the country of purchase: 
From Europa [http://europa.eu/youreurope/citizens/consumers/shopping/vat/index_en.htm](url):
> As a private individual shopping in the EU, you should only pay VAT once, in the country where you make your purchase.

The change in rules from January 2015 is only for specific digital services.  Furthermore, goods are specifically excluded.  You wouldn't get that impression from the description of this git repository.  For example, I noticed a closed issue which related to the sale of hair extensions.  That trader should not have been effected by the change of rules as they were trading goods.

This is the guidance issued in the UK when this change occurred [https://www.gov.uk/government/publications/vat-supplying-digital-services-to-private-consumers/vat-businesses-supplying-digital-services-to-private-consumers](url):
From section "Scope"

> The new rules only apply where a UK business meets all of the following criteria:supplies digital services from the UK to another EU member state (goods and non-digital services sold over the internet are not within scope)

This scope really should be mentioned in the README.md.

**Comment by jissereitsma** [comment]
Thanks for the pointer. Indeed the information was incomplete. However, instead of completing this information, I think I should simply get back to basics: I'm not a bookkeeper, and I'm not trying to be a bookkeeper. The reason why the tax rates are offered in this repository is therefore not something I want to say much about (though you already did so for a great deal ;)). Instead this repository is only meant as a container for tax rates. Whether these tax rates apply to your case, and how they apply, is something I should not say anything about. I've modified the information a bit, so that it mentions "digital goods and services" and adds more disclaimers. Thanks for noticing!

**Comment by jissereitsma** [comment]
O, and if you think the information could be improved even more, feel free to simply open up a Pull Request on the README.md: That's what makes GitHub so great: That everybody is able to change things, instead of just raising the issue.
